name: Run tests on Push 

on:
  push:
    branches:    
      - develop

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build the Docker image
      run: docker build -t saucedemo . 
      
    - name: Run the Docker container
      run: docker run saucedemo
